version: '3.8'

services:
  db:
      image: postgres:13-alpine
      volumes: 
         - postgres_data:/var/lib/postgresql/data
      ports:
         -  "5432:5432"
      env_file: 
         - ./src/.env
  server:
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - ./backend/:/backend/
      command: uvicorn src.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
      depends_on: 
        - db
      env_file:
        - ./src/.env
      ports:
        - 8000:8000
volumes: 
    postgres_data:      

