version: '3.8'

services:
  db:
      image: postgres:11
      ports:
         -  "5432:5432"
      environment: 
         - POSTGRES_USER=postgres
         - POSTGRES_PASSWORD=postgres
         - POSTGRES_DB=test_db
  server:
      build:
        context: ./
        dockerfile: Dockerfile
      volumes:
        - ./backend/:/backend/
      command: uvicorn src.api.server:app --reload --workers 1 --host 0.0.0.0 --port 8000
      depends_on: 
        - db
      env_file:
        - ./src/.env
      ports:
        - 8000:8000
 

